baseURL = "https://wixobb.github.io/"
title = "Mirfolio"
theme = "PaperMod"
languageCode = "en-us"


[pagination]
  pagerSize = 5


[params.math]
  enable = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
 
  [params.homeInfoParams]
    Title = "Bloguma hoş geldiniz"
    Content = "Ben Mirsad. Merak edip bir şeyler öğrendiğim konularla ilgili yazıyorum." 

  [params.assets]
    disableHLJS = false


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Wixobb"
[[params.socialIcons]]
  name = "link"
  url = "https://oilmesh.vercel.app/"
[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mirsad0x00/"


[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

